### PR TITLE
upgrade to Rails 5.1.4

### PR DESCRIPTION
**Pull request by drh-stanford**
@jkeck This PR upgrades to Rails 5.0.6 but does not address the Rails 5.0.x deprecation warnings. I've deployed the branch to kurma-earthworks-dev

### CODE REVIEW

**Comment by mejackreed** [comment]
Can we check to see if non-cached downloads work?

**Comment by drh-stanford** [comment]
Do you mean GeoServer-based downloads? It does look broken :(

**Comment by mejackreed** [comment]
Yep.. not sure if this solves it https://github.com/geoblacklight/geoblacklight/pull/568 but it was reported in GeoBlacklight slack last week? by Cornell

**Comment by drh-stanford** [comment]
Our Gemfile.lock already has mime-types in it, so I think that's ok.

**Comment by drh-stanford** [comment]
The download problem was a configuration issue on -dev (missing tmp/cache/downloads). I'll verify it on stage/prod

screen shot 2017-09-18 at 2 39 20 pm

**Comment by drh-stanford** [comment]
I am seeing the following error in Chrome's dev console, but the file is downloading:

screen shot 2017-09-18 at 2 43 25 pm

**Comment by mejackreed** [comment]
@drh-stanford see the context starting here: https://geoblacklight.slack.com/archives/C0TCW03EC/p1504200063000578

Might be helpful

**Pull request merged**
