### PR TITLE
adds in autocomplete and spellcheck to application and Solr config

### LINKED ISSUE #157: When I search for "labratory" I should get results for "laboratory"
Blocked by https://github.com/geoblacklight/geoblacklight/issues/259

### PR DESCRIPTION
**Pull request by mejackreed**
Closes #157

### CODE REVIEW

**Comment by drh-stanford** [comment]
stage solr index rebuild is complete. next step is to test stage, then push solr config changes to prod and rebuild via gisDiscoveryWF mechanics.

**Comment by mejackreed** [comment]
pushed up to stage now... seems to be cool

**Comment by cbeer** [comment]
screen shot 2015-11-04 at 2 46 40 pm

**Comment by flyingzumwalt** [comment]
FYI I've just taken a pass at pulling this code into a standalone gem called blacklight_suggest.  I'll try to finish it tomorrow.

**Comment by flyingzumwalt** [comment]
Nevermind.  @jcoyne pointed me to the commit where this code went into blacklight core.

**Comment by mejackreed** [comment]
:smiley_cat:

**Pull request merged**
