### PR TITLE
Modify RecentlyAddedListComponent and its copy

### LINKED ISSUE #1316: Copy for the home page
Geospatial Datasets
Data that includes location information (coordinates) and is natively usable in GIS software and services such as ArcGIS, QGIS, WFS, and WMS. Geospatial data types include vector data, such as Shapefile, GeoJSON, and GeoPackage, and raster data, such as GeoTIFF, grid files, and georeferenced maps.

Maps
Images of paper maps that have been scanned and/or georeferenced. These digital cartographic resources cover all parts of the world and include topographical maps, historical maps, nautical charts, thematic maps, and atlases.

### PR DESCRIPTION
**Pull request by marlo-longley**
Closes #1316

Screenshot 2024-08-30 at 15 36 51

### CODE REVIEW

**Comment by marlo-longley** [comment]
I could be convinced that testing for `expect(component.count).to eq(13)` hardcoded is a bad idea and will make adding unrelated new docs annoying in the future. I just wanted to make sure the component was working.

**Comment by dnoneill** [comment]
Why would it be over (that number should be exact). Shouldn't it just be There are 36 datasets?

**Comment by marlo-longley** [comment]
I just mean if I'm working on something else and add a new fixture, this test will fail and be annoying.

**Comment by dnoneill** [comment]
No sorry that wasn't clear. The copy says `There are over <b>%{sets} datasets</b> in EarthWorks.` but that isn't actually correct there are exactly %{sets} not `over`.

**Comment by marlo-longley** [comment]
I seeeee. Thanks!

**Review by dnoneill — APPROVED** [review]

**Comment by jcoyne** [comment]
@marlo-longley this needs a rebase

**Comment by thatbudakguy** [comment]
> I just mean if I'm working on something else and add a new fixture, this test will fail and be annoying.

Seems like this is exactly what happened. I'm going to just remove that test.

**Comment by marlo-longley** [comment]
Perfect, thank you for covering Nick!!

**Pull request merged**
