### PR TITLE
tweek solr config to address geoblacklight/geoblacklight#258

### PR DESCRIPTION
**Pull request by drh-stanford**
See geoblacklight/geoblacklight#258

### CODE REVIEW

**Comment by drh-stanford** [comment]
`kurma-earthworks-dev` has this config change for testing

**Comment by mejackreed** [comment]
This seems like a great candidate to add in an integration test for testing relevance of what should come back.

The tests can live under `spec/integration/external-data` 

See https://github.com/sul-dlss/earthworks/blob/master/spec/integration/external-data/author_search_spec.rb for an example.

What do you think?

**Comment by drh-stanford** [comment]
I prefer to wait a bit until we get a better sense of what the relevancy ranking should be after hearing some comments from users. For example, I dunno what should be the top 10 hits for "New Zealand" -- the ranking looks somewhat arbitrary to me, e.g., maybe it should be sorted by score and most recent data. Another example is "new zeland lakes" reverses the rank order of the "new zeland" query but "lakes new zealand" preserves the order.

**Comment by mejackreed** [comment]
:+1: Sounds good to me!

**Pull request merged**
