### PR TITLE
tool to update Solr documents with availability score

### PR DESCRIPTION
**Pull request by drh-stanford**
Addresses #8

### CODE REVIEW

**Comment by mejackreed** [comment]
Could we pop this into a rake task?
`/lib/tasks/...`

**Comment by drh-stanford** [comment]
I think a rake task would require Capistrano/puppet because `solr.yml` only has the read endpoint for the Solr index. I'm not sure you can send an update request to that URL. @eefahy? Can we update from the load balancer or do we need to talk to a specific cluster node? I've always done the latter.

**Comment by mejackreed** [comment]
I think you can run a task like this:

```
$ SOLR_URL=http://my-solr-server:PORT/solr/core rake earthworks:update_score

**Comment by drh-stanford** [comment]
Hmmm, I was thinking that you wanted a rake task that actually updated the correct index when run by default. I can make it configurable as you describe.

**Pull request merged**
