### PR TITLE
Upgrade to Blacklight 8.4.0

### LINKED ISSUE #1282: Pin to a stable ref for blacklight in the Gemfile
Undo work done in this commit.
https://github.com/sul-dlss/earthworks/pull/1229/commits/a5c346c7f903603eb9c080e1387ab334a5824f50

List of steps is in this comment https://github.com/sul-dlss/earthworks/pull/1229/files#r1735246549.

### PR DESCRIPTION
**Pull request by jcoyne**
closes #1282

### CODE REVIEW

**Review by dnoneill — APPROVED** [review]

**Comment by dnoneill** [comment]
Approved, not sure if we want to point the css on npm and not build from gem https://github.com/sul-dlss/earthworks/pull/1229/files#r1735246549. Granted vt-arclight does this and it might not matter in the gem is stable?

**Comment by thatbudakguy** [comment]
@dnoneill can you clarify what you meant here? Don't we always have to build the styles from npm?

**Comment by dnoneill** [comment]
@thatbudakguy See comment here: https://github.com/sul-dlss/earthworks/pull/1229/files#r1735246549. This PR doesn't remove the build-css script. We used to pull directly from npm not the gem.

**Comment by thatbudakguy** [comment]
Ah, thanks for explaining. Honestly, pulling from the gem makes it easier to get updates more quickly, and since few other people are working on the 5.x branch, it might be beneficial for the time being...

**Pull request merged**
