### PR TITLE
Update name of solr-core in docker

### PR DESCRIPTION
**Pull request by peetucket**
Solr core names differ from solr-wrapper to Docker.  This may reduce some confusion.

This makes them the same so the README instructions are correct.

### CODE REVIEW

**Comment by thatbudakguy** [comment]
can we just change https://github.com/sul-dlss/earthworks/blob/264feeb834b84de5226b0d2f80c2a0f3d7f6690b/docker-compose.yml#L45

to `blacklight-core` ? I think that's pretty standard among blacklight apps and then there wouldn't be any confusion

**Comment by peetucket** [comment]
> can we just change
> 
> https://github.com/sul-dlss/earthworks/blob/264feeb834b84de5226b0d2f80c2a0f3d7f6690b/docker-compose.yml#L45
> 
> to `blacklight-core` ? I think that's pretty standard among blacklight apps and then there wouldn't be any confusion

maybe, happy to experiment with this (not really clear what `entrypoint` config means and if there are other bits that would need to be updated

**Comment by hudajkhan** [comment]
There is also this line here: https://github.com/sul-dlss/earthworks/blob/main/docker-compose.yml#L14 . I think it is fine for this to go in either direction (i.e. changing the docker solr or updating the readme with the instructions in the PR), as long as the instructions are clear.

**Comment by peetucket** [comment]
OK, seemed to work to just change the core name.  Brought it down, brought it backup, tried the fixture create and it seemed to work.  Amending this PR to do this and remove the change to the readme.

**Review by hudajkhan — APPROVED** [review]

**Pull request merged**
